apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-02833
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 90Mi
  storageClassName: local-storage