apiVersion: v1
kind: Pod
metadata:
  name: log-collector
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    name: busybox
    volumeMounts:
    - mountPath: /var/log
      name: logvol
  volumes:
  - name: logvol
    emptyDir: {}