apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-03833
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard